### ISSUE TITLE
"curator-like", "curator-style", but is it curator-compatible?

### ISSUE THREAD

**Issue by meirf** [foursquare/fsgo#28]
I have Java servers that use Apache Curator. I want my go servers to be able to discover the java servers. Is the curator library [here](https://github.com/foursquare/fsgo/tree/master/net/discovery) just in the style of Apache curator or is actually compatible with Apache curator?

Your docs include ""curator-like", "curator-style", but is it also correct to say "curator-compatible"?

**Comment by theevocater** [comment]
Hi! We actually do the same, but in reverse. We use the net/discovery library in our [quiver](https://github.com/foursquare/quiver) project and discover them in java with vanilla apache curator. So it should work! 

It's mostly just a wrapper around https://github.com/curator-go/curator, which you should definitely check out as well.
