### ISSUE TITLE
including path in connection string

### ISSUE THREAD

**Issue by meirf** [foursquare/fsgo#29]
When using apache curator in java, I am able to have a zookeeper connection string like [this](http://stackoverflow.com/a/40125613/1168364):

> "127.0.0.1:3000,127.0.0.1:3001,127.0.0.1:3002/app/a" where the client would be rooted at "/app/a" and all paths would be relative to this root

Please confirm whether it is possible to do so with [discovery](https://github.com/foursquare/fsgo/tree/master/net/discovery). 

From my testing, I **could** do:
`NewServiceDiscoveryAndConn("a.b.c.d:1234", "/foo/bar")`

But I **could not** do any of these:
`NewServiceDiscoveryAndConn("a.b.c.d:1234/foo", "bar")`
`NewServiceDiscoveryAndConn("a.b.c.d:1234/foo", "/bar")`
`NewServiceDiscoveryAndConn("a.b.c.d:1234/foo", "bar/")`
`NewServiceDiscoveryAndConn("a.b.c.d:1234/foo", "/bar/")`
`NewServiceDiscoveryAndConn("a.b.c.d:1234/foo/", "bar")`
`NewServiceDiscoveryAndConn("a.b.c.d:1234/foo/", "/bar")`
`NewServiceDiscoveryAndConn("a.b.c.d:1234/foo/", "bar/")` 
`NewServiceDiscoveryAndConn("a.b.c.d:1234/foo/", "/bar/")`

Not the end of the world if I can't, I just would like to know if there's a way to get this working expecting the old behavior of allowing paths in connection strings.

**Comment by theevocater** [comment]
Hey again @meirf!

This comes from the fact that the library we use to do most of the curator heavy lifting doesn't support zookeeper roots in the connection string. The discovery library just passes the connection string directly to the [curator-go](https://github.com/curator-go/curator) library. I've worked around it like you have, but it is kind of annoying.

**Comment by PaulCapestany** [comment]
If you run the following command from the [curator-go](https://github.com/curator-go/curator) repo..

```shell
for FILE in `find . -iname "*test*"`; do egrep -nH --color 'NewClient' "$FILE"; done
```
..it looks like there are no tests that cover paths in the connection string:

```
./client_test.go:7:	NewClient("127.0.0.1:2181", nil).Start()
./recipes/cache/tree_cache_test.go:12:	curator.NewClient("127.0.0.1:2181", nil).Start()
./recipes/cache/tree_cache_test.go:621:	client := curator.NewClient(tt.serverAddr, nil)
./recipes/cache/tree_cache_utils_test.go:61:		CuratorFramework: curator.NewClient(addr, nil),
```

While I'm not super familiar with zookeeper/curator, it looks like the authors of [curator-go](https://github.com/curator-go/curator) may not be expecting the behavior... could try opening an issue over there about this?

**Comment by meirf** [comment]
Thanks for the info! One more semi-related question - if I pass multiple comma separated host:port, will the underlying library treat it as a cluster like the java version? (It looks like curator-go is not active on Github.) This is probably my last question on this.

**Comment by theevocater** [comment]
yup! the host:port,host:port,host:port should work for an arbitrary number of hosts
