### ISSUE TITLE
Fetching all instances

### ISSUE THREAD

**Issue by meirf** [foursquare/fsgo#30]
I have a requirement to get all instances for a given service. I'd like to know the most optimal/paradigmatic way of doing so.

Approach 1 (similar to [README](https://github.com/foursquare/fsgo/tree/master/net/discovery#client-side)):
```go
  s := discovery.NewServiceDiscovery(c, "/path/to/services")
  s.Watch()

  bazProvider := s.Provider("baz")
  ...
  allInstances, err := bazProvider.GetAllInstances()
```

Approach 2 (use [TreeCache](https://github.com/foursquare/fsgo/blob/master/net/discovery/tree_cache.go#L10)):
```go
  s := discovery.NewServiceDiscovery(c, "/path/to/services")
  cache := discovery.NewTreeCache(s)
  cache.Start()

  bazProvider, err := cache.Provider("baz")
  ...
  allInstances := bazProvider.GetAllInstances()
```

When `GetAllInstances` is called, does Approach 1 call zookeeper synchronously, whereas Approach 2 gets all instances from memory?

Aside from differences of Approach 1 favoring consistency and Approach 2 favoring latency, are there any other differences?

I'm assuming TreeCache has the same role as [Service Cache](http://curator.apache.org/curator-x-discovery/index.html).

**Comment by theevocater** [comment]
Your read is totally correct. Approach 2 won't need to hit the network, but is a cache maintained by watchers. I would personally stick to approach 2 if I were fetching this stuff often. It won't ever be _that_ out of date. The watchers will keep it no more than a few seconds out of date.
